### ISSUE TITLE
Vpn

### ISSUE THREAD

**Issue by jldoper** [pojntfx/weron#15]
How I can setup VPN with this program?

**Comment by pojntfx** [comment]
Hi! This depends on your OS - you need to configure it so that it routes all traffic through the VPN interface. To get the interface itself up and running, see [Create a Layer 3 (IP) Overlay Network with weron vpn ip](https://github.com/pojntfx/weron#6-create-a-layer-3-ip-overlay-network-with-weron-vpn-ip).

**Comment by pojntfx** [comment]
There are lots of ways to set this up! Be sure to enable IPv4/IPv6 forwarding on the remote host you're trying to use as your exit gateway, and use something like `iptables` to configure your client host to forward everything over weron's TAP or TUN device. Its the exact same process as with other VPNs :)

**Comment by VarLad** [comment]
@pojntfx Hey! Thanks a lot for this software! 
Can you explain the `--ips strings` command option better in `weron ip`?
Is it something related to my system I have to set, or can I just use the defaults?
